config:
  seed: 64736289
  name: default
  train: true
  test: false
  path:
    exp_root: exp
    datasets:
      wsj0_mix: data/wsj0_mix
      valentini: data/VCTK_DEMAND
    figures: figures
  datamodule:
    train:
      dl_opts:
        num_workers: 8
        shuffle: true
        batch_size: 6
      dataset:
        _target_: datasets.WSJ0_mix
        path: data/wsj0_mix
        n_spkr: 2
        fs: 8000
        cut: max
        split: train
        max_len_s: 5
        max_n_samples: null
    val:
      dl_opts:
        num_workers: 8
        shuffle: false
        batch_size: 5
      dataset:
        _target_: datasets.WSJ0_mix
        path: data/wsj0_mix
        n_spkr: 2
        fs: 8000
        cut: max
        split: val
        max_len_s: null
        max_n_samples: null
    test:
      dl_opts:
        num_workers: 8
        shuffle: false
        batch_size: 5
      dataset:
        _target_: datasets.WSJ0_mix
        path: data/wsj0_mix
        n_spkr: 2
        fs: 8000
        cut: max
        split: test
        max_len_s: null
        max_n_samples: null
  model:
    n_speakers: 2
    fs: 8000
    t_eps: 0.03
    t_rev_init: 0.03
    ema_decay: 0.999
    valid_max_sep_batches: 2
    time_sampling_strategy: uniform
    train_source_order: power
    init_hack: 5
    mmnr_thresh_pit: -10.0
    score_model:
      _target_: models.score_models.ScoreModelNCSNpp
      num_sources: 2
      stft_args:
        n_fft: 510
        hop_length: 128
        center: true
        pad_mode: constant
      backbone_args:
        _target_: models.ncsnpp.NCSNpp
        nf: 128
      transform: exponent
      spec_abs_exponent: 0.5
      spec_factor: 0.15
      spec_trans_learnable: false
    sde:
      _target_: sdes.sdes.MixSDE
      ndim: 2
      d_lambda: 2.0
      sigma_min: 0.05
      sigma_max: 0.5
      'N': 30
    sampler:
      'N': 30
      snr: 0.5
      corrector_steps: 1
    loss:
      _target_: torch.nn.MSELoss
    main_val_loss: val/si_sdr
    main_val_loss_mode: max
    val_losses:
      val/si_sdr:
        _target_: models.losses.SISDRLoss
        zero_mean: true
        clamp_db: 30
        reduction: mean
        sign_flip: true
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.0002
      weight_decay: 0.0
    scheduler: null
    grad_clipper:
      _target_: utils.FixedClipper
      max_norm: 5.0
    init_hack_p: 0.1
  trainer:
    _target_: pytorch_lightning.Trainer
    accumulate_grad_batches: 2
    min_epochs: 1
    max_epochs: 1000
    deterministic: true
    accelerator: gpu
    devices: -1
    strategy: ddp
    check_val_every_n_epoch: 5
    default_root_dir: .
    profiler: false
