_target_: pytorch_lightning.Trainer
accumulate_grad_batches: 1
min_epochs: 1
max_epochs: 500
deterministic: true
accelerator: gpu
devices: -1
strategy:
  _target_: pytorch_lightning.strategies.DDPStrategy
  find_unused_parameters: false
check_val_every_n_epoch: 10
default_root_dir: .
profiler: false
resume_from_checkpoint: null
